apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: ros-project-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: ros-project-webapi-config
    literals:
      - database=ros-ambulance
      - collection=hospital-spaces
patches:
  - path: webapi.deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: ros-project-webapi