kind: Service
apiVersion: v1
metadata:
  name: ros-project-webapi
spec:
  selector:
    pod: ros-project-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: webapi-port