server:
  port: 8080
  host: "0.0.0.0"

logging:
  level: "info"
  format: "json"

cors:
  allowed_origins:
    - "http://localhost:3000"  # Frontend development server
    - "http://localhost:3333"  # Additional frontend server
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Authorization" 