openapi: 3.0.3
info:
  contact:
    name: ROS Project Backend
    url: https://github.com/rosadsky/ros-project-backend
  license:
    name: MIT
  title: Hospital Spaces API
  version: 1.0.0
servers:
- description: Development server
  url: http://localhost:8080
tags:
- description: API health monitoring endpoints
  name: Health
- description: Hospital space management operations
  name: Spaces
- description: Ambulance management operations
  name: Ambulances
paths:
  /api/health:
    get:
      description: Check the health status of the API service
      operationId: getHealth
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getHealth_200_response'
          description: Service is healthy
      summary: Health check
      tags:
      - Health
  /api/spaces:
    get:
      description: Retrieve a list of all hospital spaces with their current status
        and assignments
      operationId: getSpaces
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Space'
                type: array
          description: List of hospital spaces
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      summary: Get all hospital spaces
      tags:
      - Spaces
    post:
      description: Create a new hospital space with the specified details
      operationId: createSpace
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpaceCreateRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Space'
          description: Space created successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request - invalid input
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      summary: Create a new hospital space
      tags:
      - Spaces
  /api/spaces/{id}:
    delete:
      description: Remove a hospital space from the system
      operationId: deleteSpace
      parameters:
      - description: The unique space ID (UUID format)
        explode: false
        in: path
        name: id
        required: true
        schema:
          example: 550e8400-e29b-41d4-a716-446655440000
          format: uuid
          type: string
        style: simple
      responses:
        "204":
          description: Space deleted successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request - invalid space ID
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Space not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      summary: Delete a hospital space
      tags:
      - Spaces
    put:
      description: "Update space assignment details such as assigned entity, type,\
        \ and ID"
      operationId: updateSpace
      parameters:
      - description: The unique space ID (UUID format)
        explode: false
        in: path
        name: id
        required: true
        schema:
          example: 550e8400-e29b-41d4-a716-446655440000
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpaceUpdateRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Space'
          description: Space updated successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request - invalid space ID or input
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Space not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      summary: Update a hospital space
      tags:
      - Spaces
  /api/ambulances:
    get:
      description: Retrieve a list of all ambulances in the system
      operationId: getAmbulances
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Ambulance'
                type: array
          description: List of ambulances
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      summary: Get all ambulances
      tags:
      - Ambulances
    post:
      description: Register a new ambulance in the system
      operationId: createAmbulance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AmbulanceCreateRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ambulance'
          description: Ambulance created successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request - invalid input
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      summary: Create a new ambulance
      tags:
      - Ambulances
components:
  schemas:
    Space:
      example:
        updated_at: 2024-01-15T14:20:00Z
        name: Emergency Room 1
        assigned_type: patient
        created_at: 2024-01-15T10:30:00Z
        id: 507f1f77bcf86cd799439011
        type: emergency_room
        floor: 2
        space_id: 550e8400-e29b-41d4-a716-446655440000
        capacity: 4
        status: available
        assigned_to: Patient John Doe
        assigned_id: 550e8400-e29b-41d4-a716-446655440001
      properties:
        id:
          description: MongoDB ObjectID
          example: 507f1f77bcf86cd799439011
          type: string
        space_id:
          description: Unique space identifier
          example: 550e8400-e29b-41d4-a716-446655440000
          format: uuid
          type: string
        name:
          description: Human-readable name of the space
          example: Emergency Room 1
          type: string
        type:
          description: Type of the hospital space
          enum:
          - emergency_room
          - operating_room
          - patient_room
          - icu
          - recovery_room
          - consultation_room
          example: emergency_room
          type: string
        floor:
          description: Floor number where the space is located
          example: 2
          minimum: 0
          type: integer
        capacity:
          description: Maximum capacity of the space
          example: 4
          minimum: 1
          type: integer
        status:
          description: Current status of the space
          enum:
          - available
          - occupied
          - maintenance
          example: available
          type: string
        assigned_to:
          description: Entity assigned to this space
          example: Patient John Doe
          nullable: true
          type: string
        assigned_type:
          description: Type of assignment
          enum:
          - patient
          - ambulance
          - equipment
          example: patient
          nullable: true
          type: string
        assigned_id:
          description: ID of the assigned entity
          example: 550e8400-e29b-41d4-a716-446655440001
          nullable: true
          type: string
        created_at:
          description: Timestamp when the space was created
          example: 2024-01-15T10:30:00Z
          format: date-time
          type: string
        updated_at:
          description: Timestamp when the space was last updated
          example: 2024-01-15T14:20:00Z
          format: date-time
          type: string
      required:
      - capacity
      - created_at
      - floor
      - name
      - space_id
      - status
      - type
      - updated_at
      type: object
    SpaceCreateRequest:
      example:
        name: Emergency Room 1
        type: emergency_room
        floor: 2
        capacity: 4
      properties:
        name:
          description: Human-readable name of the space
          example: Emergency Room 1
          maxLength: 100
          minLength: 1
          type: string
        type:
          description: Type of the hospital space
          enum:
          - emergency_room
          - operating_room
          - patient_room
          - icu
          - recovery_room
          - consultation_room
          example: emergency_room
          type: string
        floor:
          description: Floor number where the space is located
          example: 2
          maximum: 50
          minimum: 0
          type: integer
        capacity:
          description: Maximum capacity of the space
          example: 4
          maximum: 100
          minimum: 1
          type: integer
      required:
      - capacity
      - floor
      - name
      - type
      type: object
    SpaceUpdateRequest:
      description: "All fields are optional. To clear an assignment, set assigned_to\
        \ to null or empty string."
      example:
        assigned_type: patient
        assigned_to: Patient John Doe
        assigned_id: 550e8400-e29b-41d4-a716-446655440001
      properties:
        assigned_to:
          description: Entity assigned to this space (set to null or empty string
            to clear assignment)
          example: Patient John Doe
          maxLength: 200
          nullable: true
          type: string
        assigned_type:
          description: Type of assignment
          enum:
          - patient
          - ambulance
          - equipment
          example: patient
          nullable: true
          type: string
        assigned_id:
          description: ID of the assigned entity
          example: 550e8400-e29b-41d4-a716-446655440001
          nullable: true
          type: string
      type: object
    Ambulance:
      example:
        updated_at: 2024-01-15T14:20:00Z
        ambulance_id: 550e8400-e29b-41d4-a716-446655440000
        name: Ambulance Unit 1
        created_at: 2024-01-15T10:30:00Z
        location: Downtown Hospital
        id: 507f1f77bcf86cd799439011
        type: emergency
        status: available
      properties:
        id:
          description: MongoDB ObjectID
          example: 507f1f77bcf86cd799439011
          type: string
        ambulance_id:
          description: Unique ambulance identifier
          example: 550e8400-e29b-41d4-a716-446655440000
          format: uuid
          type: string
        name:
          description: Human-readable name of the ambulance
          example: Ambulance Unit 1
          type: string
        location:
          description: Current location of the ambulance
          example: Downtown Hospital
          type: string
        status:
          description: Current status of the ambulance
          enum:
          - available
          - en_route
          - busy
          - maintenance
          example: available
          type: string
        type:
          description: Type of ambulance
          enum:
          - emergency
          - transport
          - specialized
          example: emergency
          type: string
        created_at:
          description: Timestamp when the ambulance was registered
          example: 2024-01-15T10:30:00Z
          format: date-time
          type: string
        updated_at:
          description: Timestamp when the ambulance was last updated
          example: 2024-01-15T14:20:00Z
          format: date-time
          type: string
      required:
      - ambulance_id
      - created_at
      - location
      - name
      - status
      - type
      - updated_at
      type: object
    AmbulanceCreateRequest:
      example:
        name: Ambulance Unit 1
        location: Downtown Hospital
        type: emergency
      properties:
        name:
          description: Human-readable name of the ambulance
          example: Ambulance Unit 1
          maxLength: 100
          minLength: 1
          type: string
        type:
          description: Type of ambulance
          enum:
          - emergency
          - transport
          - specialized
          example: emergency
          type: string
        location:
          description: Current location of the ambulance
          example: Downtown Hospital
          maxLength: 200
          minLength: 1
          type: string
      required:
      - location
      - name
      - type
      type: object
    Error:
      example:
        error: Invalid space ID
      properties:
        error:
          description: Error message describing what went wrong
          example: Invalid space ID
          type: string
      required:
      - error
      type: object
    getHealth_200_response:
      example:
        service: hospital-spaces-api
        status: ok
      properties:
        status:
          example: ok
          type: string
        service:
          example: hospital-spaces-api
          type: string
      type: object
x-categories:
- Hospital Management
- Space Allocation
- Emergency Services
